/*
 * jQuery Hotkeys Plugin
 * Copyright 2010, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 *
 * Based upon the plugin by Tzury Bar Yochay:
 * https://github.com/tzuryby/jquery.hotkeys
 *
 * Original idea by:
 * Binny V A, http://www.openjs.com/scripts/events/keyboard_shortcuts/
 */
(function(jQuery){jQuery.hotkeys={version:"0.2.0",specialKeys:{8:"backspace",9:"tab",10:"return",13:"return",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"capslock",27:"esc",32:"space",33:"pageup",34:"pagedown",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"del",59:";",61:"=",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",106:"*",107:"+",109:"-",110:".",111:"/",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",144:"numlock",145:"scroll",173:"-",186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"`",219:"[",220:"\\",221:"]",222:"'"},shiftNums:{"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"_","=":"+",";":": ","'":'"',",":"<",".":">","/":"?","\\":"|"},textAcceptingInputTypes:["text","password","number","email","url","range","date","month","week","time","datetime","datetime-local","search","color","tel"],textInputTypes:/textarea|input|select/i,options:{filterInputAcceptingElements:true,filterTextInputs:true,filterContentEditable:true}};function t(t){if(typeof t.data==="string"){t.data={keys:t.data}}if(!t.data||!t.data.keys||typeof t.data.keys!=="string"){return}var e=t.handler,s=t.data.keys.toLowerCase().split(" ");t.handler=function(t){if(this!==t.target&&(jQuery.hotkeys.options.filterInputAcceptingElements&&jQuery.hotkeys.textInputTypes.test(t.target.nodeName)||jQuery.hotkeys.options.filterContentEditable&&jQuery(t.target).attr("contenteditable")||jQuery.hotkeys.options.filterTextInputs&&jQuery.inArray(t.target.type,jQuery.hotkeys.textAcceptingInputTypes)>-1)){return}var a=t.type!=="keypress"&&jQuery.hotkeys.specialKeys[t.which],r=String.fromCharCode(t.which).toLowerCase(),i="",n={};jQuery.each(["alt","ctrl","shift"],function(e,s){if(t[s+"Key"]&&a!==s){i+=s+"+"}});if(t.metaKey&&!t.ctrlKey&&a!=="meta"){i+="meta+"}if(t.metaKey&&a!=="meta"&&i.indexOf("alt+ctrl+shift+")>-1){i=i.replace("alt+ctrl+shift+","hyper+")}if(a){n[i+a]=true}else{n[i+r]=true;n[i+jQuery.hotkeys.shiftNums[r]]=true;if(i==="shift+"){n[jQuery.hotkeys.shiftNums[r]]=true}}for(var o=0,f=s.length;o<f;o++){if(n[s[o]]){return e.apply(this,arguments)}}}}jQuery.each(["keydown","keyup","keypress"],function(){jQuery.event.special[this]={add:t}})})(jQuery||this.jQuery||window.jQuery);
//# sourceMappingURL=jquery_hotkeys.js.map