//@ui5-bundle z/zpkw_poreport/Component-preload.js
sap.ui.require.preload({
	"z/zpkw_poreport/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","z/zpkw_poreport/model/models"],function(e,t,i){"use strict";return e.extend("z.zpkw_poreport.hd6.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"z/zpkw_poreport/controller/V_PODetail.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("z.zpkw_poreport.hd6.controller.V_PODetail",{onInit:function(){var e=sap.ui.core.UIComponent.getRouterFor(this);e.getRoute("Route_PODetail").attachMatched(this._onRouteFound,this)},_onRouteFound:function(e){var t=e.getParameter("arguments");var o=this.getView();o.bindElement({path:"/POHeaderSet('"+t.SelectedItem+"')"})},GoToHeader:function(e){var t=sap.ui.core.UIComponent.getRouterFor(this);t.navTo("Route_POHeader")},GoToPOItem:function(e){var t=e.getSource().getParent().getBindingContext().getObject().Ebeln;var o=sap.ui.core.UIComponent.getRouterFor(this);o.navTo("Route_POItem",{SelectedPO:t})}})});
},
	"z/zpkw_poreport/controller/V_POHeader.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("z.zpkw_poreport.hd6.controller.V_POHeader",{onInit:function(){},GoToPODetail:function(e){var t=e.getSource().getBindingContext().getProperty("Ebeln");var n=sap.ui.core.UIComponent.getRouterFor(this);n.navTo("Route_PODetail",{SelectedItem:t})},OnItemChange:function(e){}})});
},
	"z/zpkw_poreport/controller/V_POItem.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("z.zpkw_poreport.hd6.controller.V_POItem",{onInit:function(){var e=sap.ui.core.UIComponent.getRouterFor(this);e.getRoute("Route_POItem").attachMatched(this._onRouteFound,this)},_onRouteFound:function(e){debugger;var t=e.getParameter("arguments");var o=t.SelectedPO;var r=[];r.push(new sap.ui.model.Filter("Ebeln",sap.ui.model.FilterOperator.EQ,o));var n=this.byId("it_item").getBinding("items");n.filter(r)},GoToFirstView:function(e){var t=sap.ui.core.UIComponent.getRouterFor(this);t.navTo("Route_POHeader")},OnProcessClick:function(e){}})});
},
	"z/zpkw_poreport/controller/V_Root_View.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(o){"use strict";return o.extend("z.zpkw_poreport.hd6.controller.V_Root_View",{onInit:function(){}})});
},
	"z/zpkw_poreport/i18n/i18n.properties":'title=Title\nappTitle=zpkw_poreport\nappDescription=App Description',
	"z/zpkw_poreport/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"z.zpkw_poreport.hd6","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"servicecatalog.connectivityComponentForManifest","version":"0.0.0"},"dataSources":{"ZPKW_TEST1_SRV":{"uri":"sap/opu/odata/sap/ZPKW_TEST1_SRV/","type":"OData","settings":{"localUri":"localService/metadata.xml"}}},"crossNavigation":{"inbounds":{"zpkwporeportDisplay":{"action":"display","icon":"sap-icon://app","signature":{"additionalParameters":"allowed","parameters":{}},"semanticObject":"zpkwporeport","subTitle":"","title":"{{appTitle}}"}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"z.zpkw_poreport.hd6.view.V_Root_View","type":"XML","async":true,"id":"V_Root_View"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"z.zpkw_poreport.hd6.i18n.i18n"}},"":{"type":"sap.ui.model.odata.v2.ODataModel","settings":{"defaultOperationMode":"Server","defaultBindingMode":"OneTime","defaultCountMode":"Request","useBatch":false},"dataSource":"ZPKW_TEST1_SRV","preload":true}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"z.zpkw_poreport.hd6.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false,"viewLevel":1,"bypassed":{"target":[]}},"routes":[{"name":"Route_POHeader","pattern":"","titleTarget":"","greedy":false,"target":["Target_POHeader"]},{"name":"Route_PODetail","pattern":"POHeader{SelectedItem}","titleTarget":"","greedy":false,"target":["Target_PODetail"]},{"name":"Route_POItem","pattern":"{SelectedPO}","titleTarget":"","greedy":false,"target":["Target_POItem"]}],"targets":{"TargetV_Root_View":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"V_Root_View","viewName":"V_Root_View"},"Target_POHeader":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewName":"V_POHeader","viewLevel":1},"Target_PODetail":{"viewType":"XML","transition":"slide","clearControlAggregation":"","viewName":"V_PODetail","viewLevel":2},"Target_POItem":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewName":"V_POItem","title":"PO Item List","viewLevel":3},"v_test":{"viewType":"HTML","viewName":"v_test"}}}},"sap.cloud":{"public":true,"service":"comerpisshiperpzpkwporeport"}}',
	"z/zpkw_poreport/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"z/zpkw_poreport/serviceBinding.js":'function initModel(){var a="/sap/opu/odata/sap/ZPKW_TEST1_SRV/";var e=new sap.ui.model.odata.ODataModel(a,true);sap.ui.getCore().setModel(e)}\n',
	"z/zpkw_poreport/view/V_PODetail.view.xml":'<mvc:View xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" controllerName="z.zpkw_poreport.hd6.controller.V_PODetail"><App><pages><Page title="Purchase Order Detail" showNavButton="true" navButtonPress="GoToHeader"><content><VBox width="100%" direction="Column" id="vbox0"><items><Text xmlns="sap.m" text="PO Number: {Ebeln}" id="text7"/><Text xmlns="sap.m" text="Company Code: {Bukrs}" id="text11"/><Text xmlns="sap.m" text="PO Type: {Bsart}" id="text10"/><Text xmlns="sap.m" text="Payment Terms: {Zterm}" id="text9"/><Text xmlns="sap.m" text="Created by: {Ernam}" id="text8"/></items></VBox><Button xmlns="sap.m" text="PO Item list" id="button0" press="GoToPOItem" icon="sap-icon://arrow-right"/></content></Page></pages></App></mvc:View>',
	"z/zpkw_poreport/view/V_POHeader.view.xml":'<mvc:View xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" controllerName="z.zpkw_poreport.hd6.controller.V_POHeader"><App><pages><Page title="Purchase Order Overview"><content><Select xmlns="sap.m" id="select2" items="{/POHeaderSet}" change="OnItemChange"><items><core:Item xmlns:core="sap.ui.core" key="item-key-1" text="{Ebeln}" id="item5"/></items></Select><List noDataText="Drop list items here" id="list4" items="{/POHeaderSet}"><items><StandardListItem type="Navigation" title="PO# {Ebeln}" id="item7" press="GoToPODetail"/></items></List></content></Page></pages></App></mvc:View>',
	"z/zpkw_poreport/view/V_POItem.view.xml":'<mvc:View xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" controllerName="z.zpkw_poreport.hd6.controller.V_POItem"><App><pages><Page title="PO List Item" showNavButton="true" navButtonPress="GoToFirstView"><content><Button xmlns="sap.m" text="Button" id="button0" press="OnProcessClick"/><Table noDataText="Drop column list items here and columns in the area above" id="it_item" items="{/POItemSet}"><items><ColumnListItem type="Active" id="item0"><cells><Text text="{Ebeln}" id="text0"/><Text text="{Ebelp}" id="text1"/><Text text="{Menge}" id="text2"/><Text xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" text="{Matnr}" id="text2_copy"/><Text xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" text="{Werks}" id="text2_copy2"/><Text xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" text="{Statu}" id="text2_copy3"/></cells></ColumnListItem></items><columns><Column id="column0"><header><Label text="PO Document No" id="label0"/></header></Column><Column id="column1"><header><Label text="PO Doc Item" id="label1"/></header></Column><Column id="column2"><header><Label text="Quantity" id="label2"/></header></Column><Column xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" id="column2_copy"><header><Label text="Material" id="label2_copy"/></header></Column><Column xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" id="column2_copy2"><header><Label text="Plant" id="label2_copy2"/></header></Column><Column xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" id="column2_copy4"><header><Label text="Status" id="label2_copy4"/></header></Column></columns></Table></content></Page></pages></App></mvc:View>',
	"z/zpkw_poreport/view/V_Root_View.view.xml":'<mvc:View controllerName="z.zpkw_poreport.hd6.controller.V_Root_View" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><content></content></Page></pages></App></Shell></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
